//! The daemon's configuration file.
//!
//! Every key here reaches something real. That is a deliberate constraint rather than an
//! observation: the previous configuration declared `worker_threads`, `enable_simd`,
//! `enable_zero_copy`, `max_connections`, `poll_interval_us`, `hash_block_size`,
//! `ignore_binary`, `max_file_size`, rate limits and an API key, none of which were read by
//! anything. A knob that does nothing is worse than a missing one, because turning it feels
//! like an answer.
//!
//! Unknown keys are therefore rejected rather than ignored, so a typo — or a key left over from
//! an older file — fails `retrigger validate` instead of quietly doing nothing.

use std::net::{IpAddr, SocketAddr};
use std::path::{Path, PathBuf};
use std::time::Duration;

use anyhow::{bail, Context, Result};
use retrigger_system::{
    AwaitWriteFinishConfig, BackendMode, EventFilter, ProcessorConfig, WatcherConfig,
};
use serde::{Deserialize, Serialize};

/// The file name `start`, `validate`, and `config` reach for when none is given.
pub const DEFAULT_CONFIG_FILE: &str = "retrigger.toml";

/// Header written above a generated configuration file.
const GENERATED_HEADER: &str = "\
# Retrigger daemon configuration.
#
# Generated by `retrigger config`. Every key below is read by the daemon; unknown
# keys are rejected, so `retrigger validate` will tell you about a typo rather
# than ignoring it.
";

/// Appended when a generated file has no watch roots, which is the default.
const WATCH_PATH_HINT: &str = "
# Nothing is watched until a root is declared. Add one table per root; paths can
# also be added and removed at runtime with `POST /watch` and `POST /unwatch`.
#
# [[watcher.paths]]
# path = \"/srv/app\"
# recursive = true
";

/// The whole configuration file.
#[derive(Debug, Clone, Default, PartialEq, Eq, Serialize, Deserialize)]
#[serde(default, deny_unknown_fields)]
pub struct DaemonConfig {
    /// Where the HTTP API listens.
    pub server: ServerConfig,
    /// What is watched, and how the event stream is bounded.
    pub watcher: WatchConfig,
    /// Which paths are worth reporting.
    pub patterns: PatternConfig,
    /// How the daemon talks about itself.
    pub logging: LoggingConfig,
}

/// HTTP listener settings.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(default, deny_unknown_fields)]
pub struct ServerConfig {
    /// Address to bind. Must be a literal IP: `127.0.0.1` keeps the daemon off the network,
    /// `0.0.0.0` exposes it to anything that can route to the host.
    ///
    /// There is no authentication. Binding this anywhere but a loopback address hands every
    /// reachable process the ability to read your source tree's change stream and to make the
    /// daemon watch arbitrary paths, so do it only behind something that controls access.
    pub bind_address: String,
    /// Port to bind. `0` asks the OS for an ephemeral port, which is useful for tests and for
    /// running more than one daemon; the address actually bound is logged at startup and
    /// reported by `GET /status`.
    pub port: u16,
}

/// Watching and content-hashing settings.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(default, deny_unknown_fields)]
pub struct WatchConfig {
    /// Bounded queue size, in events. Overflow raises a rescan signal rather than losing changes
    /// silently.
    pub queue_capacity: usize,
    /// Leading-edge coalescing window in milliseconds. `0` disables coalescing.
    pub debounce_ms: u64,
    /// Whether the backend follows symbolic links when recursing.
    pub follow_symlinks: bool,
    /// Hard ceiling on cached content fingerprints.
    pub hash_cache_size: usize,
    /// How long a cached fingerprint is trusted, in seconds.
    pub hash_cache_ttl_secs: u64,
    /// Fold an atomic-save `RenamedTo` for a path already seen to arrive into `Modified`. See
    /// [`retrigger_system::WatcherConfig::atomic_write_normalization`].
    pub atomic_write_normalization: bool,
    /// Which backend drives event delivery.
    ///
    /// Declared after the scalar fields above and before `paths`: TOML requires every `key =
    /// value` in a table to precede its nested `[section]` tables, and an array of tables like
    /// `paths` must come last of all.
    pub backend: BackendConfig,
    /// Hold a changed file until it stops growing before reporting it.
    pub await_write_finish: AwaitWriteFinishSetting,
    /// Paths watched at startup. More can be added at runtime with `POST /watch`.
    ///
    /// Declared last because TOML requires scalars and tables to precede an array of tables in a
    /// serialized section. Skipped when empty so that a generated file does not contain `paths =
    /// []`, which would make appending the `[[watcher.paths]]` block the comments suggest a
    /// duplicate-key error.
    #[serde(skip_serializing_if = "Vec::is_empty")]
    pub paths: Vec<WatchPath>,
}

/// [`WatchConfig::backend`]: which backend implementation drives event delivery.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(default, deny_unknown_fields)]
pub struct BackendConfig {
    /// `"auto"` picks the platform-native backend; `"poll"` forces the portable,
    /// interval-driven fallback for network/remote file systems where kernel watch events
    /// cannot be trusted.
    pub mode: BackendModeSetting,
    /// Re-scan interval in milliseconds. Only meaningful for `mode = "poll"`.
    pub poll_interval_ms: u64,
    /// Also hash file contents on each poll, to catch a same-size, same-mtime rewrite that
    /// `stat` alone would miss. Only meaningful for `mode = "poll"`.
    pub poll_compare_contents: bool,
}

/// [`BackendConfig::mode`].
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, Default)]
#[serde(rename_all = "lowercase")]
pub enum BackendModeSetting {
    /// The platform-native backend, selected at compile time. The default.
    #[default]
    Auto,
    /// `notify`'s portable polling backend.
    Poll,
}

/// [`WatchConfig::await_write_finish`]: coalesce a chunked write into one final event.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(default, deny_unknown_fields)]
pub struct AwaitWriteFinishSetting {
    /// Off by default, which preserves the daemon's original behaviour: a change is reported as
    /// soon as the backend sees it.
    pub enabled: bool,
    /// How often to re-`stat` a path while waiting for it to settle.
    pub poll_interval_ms: u64,
    /// How long a path's size and modification time must be unchanged before it is reported.
    pub stability_threshold_ms: u64,
}

/// One watched root.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct WatchPath {
    /// The directory (or single file) to watch.
    pub path: PathBuf,
    /// Whether to watch the whole subtree.
    #[serde(default = "yes")]
    pub recursive: bool,
}

/// Include/exclude globs, applied before an event is queued.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(default, deny_unknown_fields)]
pub struct PatternConfig {
    /// Globs a path must match to be reported. Empty means "no restriction".
    pub include: Vec<String>,
    /// Globs that reject a path. Excludes beat includes.
    pub exclude: Vec<String>,
}

/// How log output is produced.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(default, deny_unknown_fields)]
pub struct LoggingConfig {
    /// `error`, `warn`, `info`, `debug`, or `trace`. Any `RUST_LOG` in the environment wins.
    pub level: LogLevel,
    /// Output shape.
    pub format: LogFormat,
}

/// Verbosity floor.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum LogLevel {
    /// Only failures.
    Error,
    /// Failures and degradations.
    Warn,
    /// Lifecycle events. The default.
    Info,
    /// Per-event detail.
    Debug,
    /// Everything, including the backend's own chatter.
    Trace,
}

/// Log output shape.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum LogFormat {
    /// Human-readable, one line per event. The default.
    Compact,
    /// Human-readable, multi-line, with source locations.
    Pretty,
    /// One JSON object per line, for log shippers.
    Json,
}

impl LogLevel {
    /// The `tracing` directive this level corresponds to.
    #[must_use]
    pub fn directive(self) -> &'static str {
        match self {
            Self::Error => "error",
            Self::Warn => "warn",
            Self::Info => "info",
            Self::Debug => "debug",
            Self::Trace => "trace",
        }
    }
}

const fn yes() -> bool {
    true
}

impl Default for ServerConfig {
    fn default() -> Self {
        Self {
            bind_address: "127.0.0.1".to_owned(),
            port: 9090,
        }
    }
}

impl Default for WatchConfig {
    fn default() -> Self {
        Self {
            queue_capacity: retrigger_system::DEFAULT_CAPACITY,
            debounce_ms: u64::try_from(retrigger_system::DEFAULT_DEBOUNCE.as_millis())
                .unwrap_or(50),
            follow_symlinks: true,
            hash_cache_size: ProcessorConfig::default().max_entries,
            hash_cache_ttl_secs: ProcessorConfig::default().ttl.as_secs(),
            atomic_write_normalization: false,
            backend: BackendConfig::default(),
            await_write_finish: AwaitWriteFinishSetting::default(),
            paths: Vec::new(),
        }
    }
}

impl Default for BackendConfig {
    fn default() -> Self {
        Self {
            mode: BackendModeSetting::Auto,
            poll_interval_ms: 1000,
            poll_compare_contents: false,
        }
    }
}

impl Default for AwaitWriteFinishSetting {
    fn default() -> Self {
        Self {
            enabled: false,
            poll_interval_ms: 100,
            stability_threshold_ms: 2000,
        }
    }
}

impl BackendConfig {
    /// The [`BackendMode`] this section describes.
    fn to_backend_mode(&self) -> BackendMode {
        match self.mode {
            BackendModeSetting::Auto => BackendMode::Auto,
            BackendModeSetting::Poll => BackendMode::Poll {
                interval: Duration::from_millis(self.poll_interval_ms),
                compare_contents: self.poll_compare_contents,
            },
        }
    }
}

impl AwaitWriteFinishSetting {
    /// The [`AwaitWriteFinishConfig`] this section describes, or `None` when disabled.
    fn to_config(&self) -> Option<AwaitWriteFinishConfig> {
        self.enabled.then(|| AwaitWriteFinishConfig {
            poll_interval: Duration::from_millis(self.poll_interval_ms),
            stability_threshold: Duration::from_millis(self.stability_threshold_ms),
        })
    }
}

impl Default for PatternConfig {
    fn default() -> Self {
        // Excluding these by default is a judgement call the watcher library deliberately does
        // not make for its callers. It is defensible here because the daemon writes this list
        // into the file `retrigger config` generates, so it is visible rather than silent — and
        // because watching a `node_modules` tree is the fastest way to exhaust inotify.
        Self {
            include: Vec::new(),
            exclude: [
                "**/node_modules/**",
                "**/.git/**",
                "**/target/**",
                "**/dist/**",
                "**/.next/**",
                "**/*.tmp",
                "**/*.swp",
                "**/*~",
                "**/.DS_Store",
            ]
            .iter()
            .map(|s| (*s).to_owned())
            .collect(),
        }
    }
}

impl Default for LoggingConfig {
    fn default() -> Self {
        Self {
            level: LogLevel::Info,
            format: LogFormat::Compact,
        }
    }
}

impl DaemonConfig {
    /// Read and parse a configuration file.
    ///
    /// # Errors
    ///
    /// If the file cannot be read, is not valid TOML, contains a key the daemon does not read,
    /// or fails [`validate`](Self::validate).
    pub fn load(path: &Path) -> Result<Self> {
        let text = std::fs::read_to_string(path)
            .with_context(|| format!("could not read {}", path.display()))?;
        let config =
            Self::parse(&text).with_context(|| format!("could not parse {}", path.display()))?;
        config
            .validate()
            .with_context(|| format!("{} is not a usable configuration", path.display()))?;
        Ok(config)
    }

    /// Parse TOML without validating it.
    ///
    /// # Errors
    ///
    /// If the text is not valid TOML for this schema.
    pub fn parse(text: &str) -> Result<Self> {
        toml::from_str(text).map_err(Into::into)
    }

    /// Render as a TOML file, with the header `retrigger config` writes.
    ///
    /// # Errors
    ///
    /// If serialization fails, which for this schema means a bug in this crate.
    pub fn to_toml(&self) -> Result<String> {
        let body = toml::to_string_pretty(self).context("could not serialize the configuration")?;
        // A daemon with no watch roots starts and watches nothing, so a generated file has to
        // say how to give it some. Appended rather than placed in the header because
        // `[[watcher.paths]]` must follow the section it belongs to.
        let hint = if self.watcher.paths.is_empty() {
            WATCH_PATH_HINT
        } else {
            ""
        };
        Ok(format!("{GENERATED_HEADER}\n{body}{hint}"))
    }

    /// Check every constraint the daemon relies on before it starts.
    ///
    /// This is what `retrigger validate` runs, and what `retrigger start` runs before it touches
    /// a socket or a kernel watch. It deliberately does *not* check that watched paths exist:
    /// a configuration can legitimately be validated on a machine that is not the one it will
    /// run on. `start` reports a missing path when it tries to watch it.
    ///
    /// # Errors
    ///
    /// If the bind address is not a literal IP, a size is zero, or a glob does not compile.
    pub fn validate(&self) -> Result<()> {
        self.socket_addr()?;

        if self.watcher.queue_capacity == 0 {
            bail!("watcher.queue_capacity must be at least 1");
        }
        if self.watcher.hash_cache_size == 0 {
            bail!("watcher.hash_cache_size must be at least 1");
        }
        for entry in &self.watcher.paths {
            if entry.path.as_os_str().is_empty() {
                bail!("watcher.paths contains an entry with an empty path");
            }
        }
        if self.watcher.backend.mode == BackendModeSetting::Poll
            && self.watcher.backend.poll_interval_ms == 0
        {
            bail!("watcher.backend.poll_interval_ms must be at least 1 when mode = \"poll\"");
        }
        if self.watcher.await_write_finish.enabled {
            if self.watcher.await_write_finish.poll_interval_ms == 0 {
                bail!(
                    "watcher.await_write_finish.poll_interval_ms must be at least 1 when enabled"
                );
            }
            if self.watcher.await_write_finish.stability_threshold_ms == 0 {
                bail!(
                    "watcher.await_write_finish.stability_threshold_ms must be at least 1 when \
                     enabled"
                );
            }
        }
        // Compiling the filter is the only honest way to validate the globs: it is the same
        // code path, so a pattern that passes here cannot fail at startup.
        self.filter()?;
        Ok(())
    }

    /// The address the HTTP server should bind.
    ///
    /// # Errors
    ///
    /// If `server.bind_address` is not a literal IPv4 or IPv6 address. Host names are rejected
    /// on purpose: resolving one can yield several addresses, and a daemon that binds a
    /// different interface than the operator meant is a security problem, not a convenience.
    pub fn socket_addr(&self) -> Result<SocketAddr> {
        let ip: IpAddr = self.server.bind_address.parse().with_context(|| {
            format!(
                "server.bind_address must be a literal IP address such as 127.0.0.1 or ::1, \
                 got {:?}",
                self.server.bind_address
            )
        })?;
        Ok(SocketAddr::new(ip, self.server.port))
    }

    /// The compiled include/exclude filter.
    ///
    /// # Errors
    ///
    /// If any glob fails to compile.
    pub fn filter(&self) -> Result<EventFilter> {
        EventFilter::from_globs(&self.patterns.include, &self.patterns.exclude)
            .context("invalid pattern in [patterns]")
    }

    /// The watcher configuration this file describes.
    ///
    /// # Errors
    ///
    /// If any glob in `[patterns]` fails to compile.
    pub fn watcher_config(&self) -> Result<WatcherConfig> {
        Ok(WatcherConfig {
            capacity: self.watcher.queue_capacity,
            debounce: Duration::from_millis(self.watcher.debounce_ms),
            follow_symlinks: self.watcher.follow_symlinks,
            filter: self.filter()?,
            backend: self.watcher.backend.to_backend_mode(),
            await_write_finish: self.watcher.await_write_finish.to_config(),
            atomic_write_normalization: self.watcher.atomic_write_normalization,
        })
    }

    /// The content-fingerprint cache configuration this file describes.
    #[must_use]
    pub fn processor_config(&self) -> ProcessorConfig {
        ProcessorConfig {
            max_entries: self.watcher.hash_cache_size,
            ttl: Duration::from_secs(self.watcher.hash_cache_ttl_secs),
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn defaults_are_valid_and_round_trip_through_toml() -> Result<()> {
        let config = DaemonConfig::default();
        config.validate()?;

        let rendered = config.to_toml()?;
        assert!(rendered.starts_with('#'), "the header should survive");
        assert_eq!(
            DaemonConfig::parse(&rendered)?,
            config,
            "a generated file must parse back to what generated it"
        );
        Ok(())
    }

    #[test]
    fn a_watch_root_can_be_appended_to_a_generated_file() -> Result<()> {
        // The obvious first thing anyone does with `retrigger config` is append a path to it.
        // That has to parse: an emitted `paths = []` would make it a duplicate-key error.
        let generated = DaemonConfig::default().to_toml()?;
        assert!(
            !generated.contains("paths = []"),
            "an empty array would collide with an appended [[watcher.paths]]:\n{generated}"
        );
        assert!(
            generated.contains("# [[watcher.paths]]"),
            "the file must show how to add a watch root:\n{generated}"
        );

        let appended =
            format!("{generated}\n[[watcher.paths]]\npath = \"/srv/app\"\nrecursive = true\n");
        let config = DaemonConfig::parse(&appended)?;
        config.validate()?;
        assert_eq!(config.watcher.paths.len(), 1);
        assert_eq!(config.watcher.paths[0].path, PathBuf::from("/srv/app"));

        // And a file that already has roots round-trips with them intact.
        let rendered = config.to_toml()?;
        assert_eq!(DaemonConfig::parse(&rendered)?, config);
        Ok(())
    }

    #[test]
    fn the_config_shipped_in_the_npm_package_still_matches_this_schema() -> Result<()> {
        // `src/daemon/config/retrigger.toml` is published in the `@retrigger/daemon` tarball, so
        // a key removed here has to be removed there too. The previous file described `[ipc]`,
        // `[security]`, and a blake3 hash setting, none of which ever existed.
        let path = Path::new(env!("CARGO_MANIFEST_DIR")).join("../config/retrigger.toml");
        let text = std::fs::read_to_string(&path)
            .with_context(|| format!("could not read {}", path.display()))?;

        let shipped = DaemonConfig::parse(&text)
            .with_context(|| format!("{} no longer parses", path.display()))?;
        shipped.validate()?;
        assert_eq!(
            shipped,
            DaemonConfig::default(),
            "the shipped file should stay the generated default"
        );
        Ok(())
    }

    #[test]
    fn an_empty_file_is_the_default_configuration() -> Result<()> {
        assert_eq!(DaemonConfig::parse("")?, DaemonConfig::default());
        Ok(())
    }

    #[test]
    fn every_section_is_optional() -> Result<()> {
        let config = DaemonConfig::parse("[server]\nport = 1234\n")?;
        assert_eq!(config.server.port, 1234);
        assert_eq!(
            config.server.bind_address,
            DaemonConfig::default().server.bind_address
        );
        assert_eq!(config.watcher, DaemonConfig::default().watcher);
        Ok(())
    }

    #[test]
    fn a_key_the_daemon_does_not_read_is_an_error() {
        // The whole point of `deny_unknown_fields`: the old file's fictional knobs must not be
        // silently accepted, and neither must a typo.
        for text in [
            "[server]\nenable_metrics = true\n",
            "[watcher]\nevent_buffer_size = 10\n",
            "[performance]\nenable_simd = true\n",
            "[ipc]\nmmap_path = \"/tmp/x\"\n",
            "[server]\nprot = 1\n",
        ] {
            let err = DaemonConfig::parse(text).expect_err("should be rejected");
            assert!(
                err.to_string().contains("unknown field"),
                "expected an unknown-field error for {text:?}, got: {err}"
            );
        }
    }

    #[test]
    fn watch_paths_parse_with_recursive_defaulting_to_true() -> Result<()> {
        let config = DaemonConfig::parse(
            r#"
[[watcher.paths]]
path = "/srv/app"

[[watcher.paths]]
path = "/srv/other"
recursive = false
"#,
        )?;
        assert_eq!(config.watcher.paths.len(), 2);
        assert!(config.watcher.paths[0].recursive);
        assert!(!config.watcher.paths[1].recursive);
        assert_eq!(config.watcher.paths[1].path, PathBuf::from("/srv/other"));
        Ok(())
    }

    #[test]
    fn a_host_name_is_not_an_acceptable_bind_address() {
        let config = DaemonConfig::parse("[server]\nbind_address = \"localhost\"\n")
            .expect("parses; it is only invalid semantically");
        let err = config.validate().expect_err("localhost must be rejected");
        assert!(
            err.to_string().contains("literal IP"),
            "the error should say what to write instead, got: {err}"
        );
    }

    #[test]
    fn ipv6_and_wildcard_addresses_are_accepted() -> Result<()> {
        for (address, port) in [("::1", 1u16), ("0.0.0.0", 9090), ("127.0.0.1", 0)] {
            let config = DaemonConfig::parse(&format!(
                "[server]\nbind_address = {address:?}\nport = {port}\n"
            ))?;
            config.validate()?;
            assert_eq!(config.socket_addr()?.port(), port);
        }
        Ok(())
    }

    #[test]
    fn zero_sized_buffers_are_rejected() {
        for text in [
            "[watcher]\nqueue_capacity = 0\n",
            "[watcher]\nhash_cache_size = 0\n",
        ] {
            let config = DaemonConfig::parse(text).expect("parses");
            assert!(
                config.validate().is_err(),
                "a zero-sized buffer must not be accepted: {text:?}"
            );
        }
    }

    #[test]
    fn a_broken_glob_fails_validation_rather_than_startup() {
        let config = DaemonConfig::parse("[patterns]\ninclude = [\"src/[\"]\n").expect("parses");
        let err = config.validate().expect_err("an unclosed class must fail");
        assert!(
            format!("{err:#}").contains("pattern"),
            "the error should point at the pattern, got: {err:#}"
        );
    }

    #[test]
    fn an_empty_watch_path_is_rejected() {
        let config = DaemonConfig::parse("[[watcher.paths]]\npath = \"\"\n").expect("parses");
        assert!(config.validate().is_err());
    }

    #[test]
    fn patterns_become_the_filter_the_watcher_actually_uses() -> Result<()> {
        let config = DaemonConfig::parse(
            r#"
[patterns]
include = ["**/*.rs"]
exclude = ["**/target/**"]
"#,
        )?;
        let filter = config.filter()?;
        assert!(filter.matches(Path::new("/p/src/main.rs")));
        assert!(!filter.matches(Path::new("/p/target/debug/build.rs")));
        assert!(!filter.matches(Path::new("/p/README.md")));
        Ok(())
    }

    #[test]
    fn watcher_and_processor_settings_are_carried_through() -> Result<()> {
        let config = DaemonConfig::parse(
            r"
[watcher]
queue_capacity = 17
debounce_ms = 0
follow_symlinks = false
hash_cache_size = 5
hash_cache_ttl_secs = 9
",
        )?;
        let watcher = config.watcher_config()?;
        assert_eq!(watcher.capacity, 17);
        assert_eq!(watcher.debounce, Duration::ZERO);
        assert!(!watcher.follow_symlinks);

        let processor = config.processor_config();
        assert_eq!(processor.max_entries, 5);
        assert_eq!(processor.ttl, Duration::from_secs(9));
        Ok(())
    }

    #[test]
    fn backend_and_await_write_finish_default_to_the_original_behaviour() {
        let config = DaemonConfig::default();
        assert_eq!(config.watcher.backend.mode, BackendModeSetting::Auto);
        assert!(!config.watcher.await_write_finish.enabled);
        assert!(!config.watcher.atomic_write_normalization);

        let watcher = config.watcher_config().expect("valid");
        assert_eq!(watcher.backend, retrigger_system::BackendMode::Auto);
        assert_eq!(watcher.await_write_finish, None);
        assert!(!watcher.atomic_write_normalization);
    }

    #[test]
    fn a_poll_backend_and_await_write_finish_are_carried_through() -> Result<()> {
        let config = DaemonConfig::parse(
            r#"
[watcher.backend]
mode = "poll"
poll_interval_ms = 250
poll_compare_contents = true

[watcher.await_write_finish]
enabled = true
poll_interval_ms = 20
stability_threshold_ms = 400
"#,
        )?;
        config.validate()?;
        let watcher = config.watcher_config()?;
        assert_eq!(
            watcher.backend,
            retrigger_system::BackendMode::Poll {
                interval: Duration::from_millis(250),
                compare_contents: true,
            }
        );
        assert_eq!(
            watcher.await_write_finish,
            Some(AwaitWriteFinishConfig {
                poll_interval: Duration::from_millis(20),
                stability_threshold: Duration::from_millis(400),
            })
        );
        Ok(())
    }

    #[test]
    fn a_zero_poll_interval_is_rejected_only_when_the_section_using_it_is_active() -> Result<()> {
        // `mode = "auto"` never reads `poll_interval_ms`, so a stray 0 left over from switching
        // back from `"poll"` must not fail validation.
        let inert =
            DaemonConfig::parse("[watcher.backend]\nmode = \"auto\"\npoll_interval_ms = 0\n")?;
        inert.validate()?;

        let active =
            DaemonConfig::parse("[watcher.backend]\nmode = \"poll\"\npoll_interval_ms = 0\n")?;
        assert!(active.validate().is_err());
        Ok(())
    }

    #[test]
    fn await_write_finish_rejects_a_zero_threshold_only_when_enabled() -> Result<()> {
        let inert =
            DaemonConfig::parse("[watcher.await_write_finish]\nstability_threshold_ms = 0\n")?;
        inert.validate()?;

        let active = DaemonConfig::parse(
            "[watcher.await_write_finish]\nenabled = true\nstability_threshold_ms = 0\n",
        )?;
        assert!(active.validate().is_err());
        Ok(())
    }

    #[test]
    fn the_default_excludes_cover_the_trees_that_exhaust_inotify() -> Result<()> {
        let filter = DaemonConfig::default().filter()?;
        assert!(!filter.matches(Path::new("/p/node_modules/react/index.js")));
        assert!(!filter.matches(Path::new("/p/.git/HEAD")));
        assert!(filter.matches(Path::new("/p/src/app.ts")));
        Ok(())
    }

    #[test]
    fn log_levels_and_formats_parse_from_lowercase_names() -> Result<()> {
        let config = DaemonConfig::parse("[logging]\nlevel = \"debug\"\nformat = \"json\"\n")?;
        assert_eq!(config.logging.level, LogLevel::Debug);
        assert_eq!(config.logging.format, LogFormat::Json);
        assert_eq!(config.logging.level.directive(), "debug");

        assert!(DaemonConfig::parse("[logging]\nlevel = \"chatty\"\n").is_err());
        Ok(())
    }

    #[test]
    fn a_missing_file_reports_the_path_it_looked_for() {
        let err = DaemonConfig::load(Path::new("/definitely/not/here/retrigger.toml"))
            .expect_err("a missing file must fail");
        assert!(
            format!("{err:#}").contains("/definitely/not/here/retrigger.toml"),
            "the error must name the file, got: {err:#}"
        );
    }

    #[test]
    fn a_malformed_file_reports_the_path_and_the_syntax_error() -> std::io::Result<()> {
        let dir = tempfile::tempdir()?;
        let path = dir.path().join("retrigger.toml");
        std::fs::write(&path, "[server\nport = ")?;

        let err = DaemonConfig::load(&path).expect_err("broken TOML must fail");
        let rendered = format!("{err:#}");
        assert!(rendered.contains("could not parse"), "got: {rendered}");
        Ok(())
    }

    #[test]
    fn load_rejects_a_file_that_parses_but_cannot_run() -> std::io::Result<()> {
        let dir = tempfile::tempdir()?;
        let path = dir.path().join("retrigger.toml");
        std::fs::write(&path, "[server]\nbind_address = \"not-an-ip\"\n")?;

        let err = DaemonConfig::load(&path).expect_err("an unbindable address must fail at load");
        assert!(format!("{err:#}").contains("literal IP"));
        Ok(())
    }
}

/// Generated round-trip and rejection properties.
///
/// The example tests above pin the shapes that matter to a human reader; these assert the same
/// contract holds across the whole space of legal files — any valid configuration renders to a
/// file that parses back to itself, and every documented rejection holds no matter what else the
/// configuration says.
#[cfg(test)]
mod property_tests {
    use super::*;
    use proptest::prelude::*;

    /// Only literal IPs, because a host name is a validation failure by design and would just be
    /// noise in the round-trip property.
    fn valid_ip() -> impl Strategy<Value = String> {
        prop_oneof![
            (any::<u8>(), any::<u8>(), any::<u8>(), any::<u8>())
                .prop_map(|(a, b, c, d)| format!("{a}.{b}.{c}.{d}")),
            Just("::1".to_owned()),
            Just("::".to_owned()),
        ]
    }

    /// ASCII paths only: the property is about the configuration schema, not about the filesystem's
    /// tolerance for exotic bytes, and every character here survives a TOML string round-trip.
    fn safe_path() -> impl Strategy<Value = PathBuf> {
        "[a-zA-Z0-9_./-]{1,32}".prop_map(PathBuf::from)
    }

    /// A pool of globs that all compile, so a generated config is rejected for the reason under
    /// test rather than for an accidental unclosed class.
    fn valid_glob() -> impl Strategy<Value = String> {
        prop_oneof![
            Just("**/*.rs".to_owned()),
            Just("src/**".to_owned()),
            Just("*.txt".to_owned()),
            Just("**/node_modules/**".to_owned()),
            Just("logs/*.log".to_owned()),
        ]
    }

    fn log_level() -> impl Strategy<Value = LogLevel> {
        prop_oneof![
            Just(LogLevel::Error),
            Just(LogLevel::Warn),
            Just(LogLevel::Info),
            Just(LogLevel::Debug),
            Just(LogLevel::Trace),
        ]
    }

    fn log_format() -> impl Strategy<Value = LogFormat> {
        prop_oneof![
            Just(LogFormat::Compact),
            Just(LogFormat::Pretty),
            Just(LogFormat::Json),
        ]
    }

    fn backend_mode() -> impl Strategy<Value = BackendModeSetting> {
        prop_oneof![
            Just(BackendModeSetting::Auto),
            Just(BackendModeSetting::Poll)
        ]
    }

    prop_compose! {
        // Starts at 1, never 0: both `poll_interval_ms` fields are validation failures at 0
        // regardless of whether the section they belong to is even active, so keeping the
        // property generator out of that space entirely means it only ever exercises
        // configurations `validate()` is supposed to accept.
        fn backend_config()(
            mode in backend_mode(),
            poll_interval_ms in 1_u64..=60_000,
            poll_compare_contents in any::<bool>(),
        ) -> BackendConfig {
            BackendConfig { mode, poll_interval_ms, poll_compare_contents }
        }
    }

    prop_compose! {
        fn await_write_finish_setting()(
            enabled in any::<bool>(),
            poll_interval_ms in 1_u64..=10_000,
            stability_threshold_ms in 1_u64..=60_000,
        ) -> AwaitWriteFinishSetting {
            AwaitWriteFinishSetting { enabled, poll_interval_ms, stability_threshold_ms }
        }
    }

    prop_compose! {
        // Sizes stay within i64 range because TOML integers are signed 64-bit; a value the format
        // cannot represent would be a TOML limitation surfacing as a false failure, not a bug here.
        fn valid_config()(
            bind_address in valid_ip(),
            port in any::<u16>(),
            queue_capacity in 1_usize..=100_000,
            debounce_ms in 0_u64..=10_000,
            follow_symlinks in any::<bool>(),
            hash_cache_size in 1_usize..=100_000,
            hash_cache_ttl_secs in 0_u64..=1_000_000,
            atomic_write_normalization in any::<bool>(),
            backend in backend_config(),
            await_write_finish in await_write_finish_setting(),
            paths in prop::collection::vec((safe_path(), any::<bool>()), 0..4),
            include in prop::collection::vec(valid_glob(), 0..3),
            exclude in prop::collection::vec(valid_glob(), 0..3),
            level in log_level(),
            format in log_format(),
        ) -> DaemonConfig {
            DaemonConfig {
                server: ServerConfig { bind_address, port },
                watcher: WatchConfig {
                    queue_capacity,
                    debounce_ms,
                    follow_symlinks,
                    hash_cache_size,
                    hash_cache_ttl_secs,
                    atomic_write_normalization,
                    backend,
                    await_write_finish,
                    paths: paths
                        .into_iter()
                        .map(|(path, recursive)| WatchPath { path, recursive })
                        .collect(),
                },
                patterns: PatternConfig { include, exclude },
                logging: LoggingConfig { level, format },
            }
        }
    }

    proptest! {
        #[test]
        fn any_valid_config_round_trips_through_toml(config in valid_config()) {
            config
                .validate()
                .map_err(|e| TestCaseError::fail(format!("generated config failed validation: {e:#}")))?;
            let rendered = config
                .to_toml()
                .map_err(|e| TestCaseError::fail(format!("could not serialize: {e:#}")))?;
            let parsed = DaemonConfig::parse(&rendered)
                .map_err(|e| TestCaseError::fail(format!("could not reparse: {e:#}")))?;
            prop_assert_eq!(parsed, config, "a rendered config must parse back to itself");
        }

        #[test]
        fn a_zero_queue_capacity_is_always_rejected(mut config in valid_config()) {
            config.watcher.queue_capacity = 0;
            prop_assert!(config.validate().is_err());
        }

        #[test]
        fn a_zero_cache_size_is_always_rejected(mut config in valid_config()) {
            config.watcher.hash_cache_size = 0;
            prop_assert!(config.validate().is_err());
        }

        #[test]
        fn an_empty_watch_path_is_always_rejected(mut config in valid_config()) {
            config.watcher.paths.push(WatchPath { path: PathBuf::new(), recursive: true });
            prop_assert!(config.validate().is_err());
        }

        #[test]
        fn a_non_ip_bind_address_is_always_rejected(
            mut config in valid_config(),
            host in "[a-z][a-z0-9.-]{0,20}",
        ) {
            prop_assume!(host.parse::<std::net::IpAddr>().is_err());
            config.server.bind_address = host;
            prop_assert!(config.validate().is_err());
        }
    }
}
